using System;
using System.Collections.Generic;

namespace PT_Readify
{
    public static class LanguageHelper
    {
        private static readonly Dictionary<string, string> Pt = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "SettingsTitle", "Configurações" },
            { "Theme", "Tema:" },
            { "ThemeLight", "Claro" },
            { "ThemeDark", "Escuro" },
            { "Fullscreen", "Modo de leitura fullscreen:" },
            { "Font", "Fonte:" },
            { "FontSize", "Tamanho (pt):" },
            { "AutoLogout", "Temporizador de desconexão:" },
            { "Language", "Linguagem:" },
            { "Save", "Salvar" },
            { "Cancel", "Cancelar" },
            { "Reset", "Restaurar Padrões" },
            { "RestoreLanguage", "Voltar à linguagem original" },
            { "Never", "Nunca" },
            { "Saved", "Configurações guardadas." },
            { "Success", "Sucesso" },
            { "ResetConfirm", "Restaurar padrões irá repor todas as preferências. Continuar?" },
            { "Confirm", "Confirmar" },
            { "NoOriginalLanguage", "Linguagem original não definida." },
            { "Info", "Informação" },
            { "LanguageRestored", "Linguagem restaurada para o original." },
            { "Logout", "Logout" },
            { "Books", "Livros" },
            { "Profile", "Perfil" },
            { "Help", "Ajuda" },
            { "Loans", "Requisições" },
            { "PurchaseHistory", "Devolução/Histórico de Compras" },
            { "LoanHistory", "Devolução/Histórico de Requisições" },
            { "Reservations", "Reservas" },
            { "Assistant", "Assistente" },
            { "AutoLogoutTitle", "Sessão expirada" },
            { "AutoLogoutMessage", "A sua sessão foi terminada por inatividade." },
            { "Close", "Fechar" },
            { "BooksInCart", "Livros ({0} no carrinho)" },
            { "Email", "Email:" },
            { "Password", "Palavra-passe:" },
            { "Login", "Login" },
            { "Welcome", "Bem-vindo" },
            { "Enter", "Entrar" },
            { "Register", "Registre-se" },
            { "ForgotPassword", "Esqueceu a password?" },
            { "NoAccount", "Ainda não tem uma conta?" },
            { "WalletTitle", "Carteira Digital" },
            { "WalletAccess", "Acesso à Carteira Digital" },
            { "EnterPassword", "Introduza a sua Password:" },
            { "MyWallet", "A Minha Carteira" },
            { "CurrentBalance", "Saldo Atual: {0:F2}€" },
            { "ChangePaymentMethod", "Alterar Forma de Pagamento" },
            { "ConfigurePayment", "Configurar Pagamento" },
            { "SelectMethod", "Selecione o método pretendido:" },
            { "PayPalEmail", "Email do PayPal:" },
            { "PhoneNumber", "Número de Telemóvel:" },
            { "AccountIBAN", "IBAN da Conta:" },
            { "AppleID", "Apple ID:" },
            { "SaveChanges", "Salvar Alterações" },
            { "Back", "Voltar" },
            { "AddFunds", "Adicionar Fundos" },
            { "EnterAmount", "Introduza o valor a carregar na carteira (€):" },
            { "CurrentBalanceLabel", "Saldo atual: {0:F2}€" },
            { "MinValue", "Valor mínimo: 1.00€ | Valor máximo: 1000.00€" },
            { "ConfirmButton", "CONFIRMAR" },
            { "CancelButton", "CANCELAR" },
            { "ConfirmLoading", "Confirmar Carregamento" },
            { "ConfirmLoadingMsg", "Confirma o carregamento de {0:F2}€?\n\nSaldo atual: {1:F2}€\nNovo saldo: {2:F2}€" },
            { "InvalidValue", "Valor inválido" },
            { "EnterValidValue", "Introduza um valor válido maior que zero." },
            { "MinValueError", "O valor mínimo é de 1.00€." },
            { "MaxValueError", "O valor máximo é de 1000.00€." },
            { "DefinePassword", "Definir Password" },
            { "DefinePasswordMsg", "Defina a sua password de acesso à Carteira Digital:" },
            { "PasswordRequirements", "• Mínimo 4 caracteres\n• Máximo 20 caracteres\n• Pode conter letras, números e símbolos" },
            { "Exit", "SAIR" },
            { "PasswordDefined", "Password definida com sucesso!" },
            { "ChangePassword", "Alterar Password" },
            { "CurrentPassword", "Password Atual:" },
            { "NewPassword", "Nova Password:" },
            { "Change", "ALTERAR" },
            { "CurrentPasswordIncorrect", "Password atual incorreta!" },
            { "PasswordChanged", "Password alterada com sucesso!" },
            { "ConfirmChange", "Confirmar Alteração" },
            { "AreYouSureChangePassword", "Tem a certeza que deseja alterar a sua password?" },
            { "PleaseEnterPassword", "Por favor, introduza a password." },
            { "PasswordCannotBeEmpty", "A password não pode estar vazia. Tente novamente." },
            { "PasswordMinChars", "A password deve ter um mínimo de 4 caracteres." },
            { "PasswordMaxChars", "A password deve ter um máximo de 20 caracteres." },
            { "WelcomeToWallet", "Bem-vindo à sua Carteira Digital!" },
            { "AuthenticationSuccessful", "Autenticação Bem-Sucedida" },
            { "AttemptsExceeded", "Tentativas de acesso excedidas!\nA aplicação será fechada." },
            { "AccessBlocked", "Acesso Bloqueado" },
            { "PasswordIncorrect", "Password incorreta!\n\nTentativas restantes: {0}" },
            { "AuthenticationError", "Erro de Autenticação" },
            { "SelectPaymentMethod", "Por favor, selecione um método de pagamento." },
            { "ValidationWarning", "Aviso de Validação" },
            { "MethodConfigured", "Método [{0}] configurado com sucesso!\nDados guardados: {1}" },
            { "FillPaymentField", "Por favor, preencha o campo de dados do método de pagamento selecionado." },
            { "InsufficientBalance", "Saldo insuficiente para completar a compra." },
            { "PurchaseSuccessful", "Compra bem-sucedida: {0}" },
            { "FundsAdded", "Fundos adicionados e guardados com sucesso: +{0:F2}€\n\nSaldo atual: {1:F2}€" },
            { "ValueMustBePositive", "O valor a adicionar deve ser positivo." },
            { "CartTitle", "Carrinho de Compras" },
            { "CartInfo", "O carrinho é apenas para compras. Para requisitar ou reservar, use Requisições." },
            { "ID", "ID" },
            { "Title", "Título" },
            { "Author", "Autor" },
            { "Publisher", "Editora" },
            { "Price", "Preço" },
            { "Qty", "Qtd" },
            { "Subtotal", "Subtotal" },
            { "Remove", "Remover" },
            { "Total", "Total: {0:C2} ({1} itens)" },
            { "RemoveConfirm", "Deseja remover este livro do carrinho?" },
            { "Confirmation", "Confirmação" },
            { "QtyGreaterThanZero", "A quantidade deve ser maior que 0." },
            { "InsufficientStock", "Stock insuficiente" },
            { "CartEmpty", "O carrinho está vazio!" },
            { "LoginToPurchase", "Inicie sessão para finalizar a compra." },
            { "InsufficientBalanceCart", "Saldo insuficiente na carteira. Total: {0:C2}" },
            { "InsufficientBalanceTitle", "Saldo insuficiente" },
            { "PurchaseCompleted", "Compra efetuada com sucesso!" },
            { "ReceiptError", "Erro ao enviar recibo: {0}" },
            { "PurchaseError", "Erro ao finalizar compra: {0}" },
            { "Error", "Erro" },
            { "ClearCartConfirm", "Deseja limpar todo o carrinho?" },
            { "Requests", "Requisições" },
            { "ProfileTitle", "Perfil" },
            { "EditProfile", "Editar" },
            { "SaveProfile", "Guardar" },
            { "EditPassword", "Editar Palavra-Passe" },
            { "ConfirmIdentity", "É necessário confirmar a sua identidade para ativar o modo de edição." },
            { "ConfirmationRequired", "Confirmação Necessária" },
            { "EditModeActivated", "Modo de edição ativado. Agora pode alterar os seus dados e clicar na foto de perfil." },
            { "ClickEditToChangePhoto", "Clique em 'Editar' para poder alterar a foto de perfil." },
            { "RestrictedAccess", "Acesso Restrito" },
            { "ViewPasswordFirst", "Para visualizar ou alterar a palavra-passe, clique primeiro em 'Editar'." },
            { "InvalidPhoneDigits", "Número de telefone inválido. Apenas dígitos são permitidos." },
            { "InvalidPhoneLength", "Número de telefone inválido. Deve conter exatamente 9 dígitos." },
            { "NameEmailRequired", "Os campos Nome e Email não podem estar vazios." },
            { "InvalidEmail", "Endereço de email inválido. Certifique-se de que contém '@' e '.'." },
            { "PasswordMinLength", "A palavra-passe deve conter pelo menos 6 caracteres." },
            { "PasswordComplexity", "A password deve conter pelo menos uma letra maiúscula, uma letra minúscula, um número e um caracter especial" },
            { "PasswordNoSpaces", "A password não pode conter espaços em branco" },
            { "DataUpdated", "Dados atualizados com sucesso!" },
            { "NoChanges", "Nenhuma alteração foi detetada." },
            { "Information", "Informação" },
            { "BookHistory", "Histórico de Livros" },
            { "PurchaseHistoryTitle", "Histórico de Compras" },
            { "LoginToViewHistory", "Inicie sessão para ver o histórico de compras." },
            { "NoPurchases", "Sem compras registadas" },
            { "PurchasesCount", "{0} compra(s)" },
            { "ReturnedCount", "{0} devolvida(s)" },
            { "SortError", "Não foi possível ordenar: dados inválidos ou coluna não encontrada." },
            { "LoginToReturn", "Inicie sessão para devolver compras." },
            { "ReturnPurchase", "Devolver Compra" },
            { "LoanHistoryTitle", "Histórico de Empréstimos" },
            { "LoginToViewLoans", "Inicie sessão para ver o histórico de empréstimos." },
            { "ReturnBook", "Devolver livro" },
            { "NoActiveLoans", "Sem empréstimos ativos" },
            { "ActiveLoans", "{0} empréstimo(s) ativo(s)" },
            { "ActiveAndOverdue", "{0} ativo(s) - {1} em atraso (multa: 2€/semana)" },
            { "SelectLoanToReturn", "Selecione um empréstimo para devolver." },
            { "SelectActiveLoan", "Selecione um empréstimo ativo para devolver." },
            { "LoanReturn", "Devolução de Empréstimo" },
            { "ErrorReturning", "Erro ao devolver: {0}" },
            { "SelectRejectedLoan", "Selecione um empréstimo rejeitado para pagar a multa." },
            { "OnlyRejectedHaveFine", "Apenas empréstimos rejeitados têm multa por livro estragado." },
            { "ConfirmFinePayment", "Confirmar Pagamento" },
            { "PayFineConfirm", "Pagar a multa por livro estragado de \"{0}\"?\n\nApós o pagamento, o livro será devolvido." },
            { "FinePaid", "Multa paga com sucesso! O livro foi devolvido." },
            { "ErrorPayingFine", "Erro ao pagar multa: {0}" },
            { "ReturnPurchaseTitle", "Devolução da Compra" },
            { "NoEligiblePurchases", "Sem compras elegíveis nos primeiros {0} dias" },
            { "EligiblePurchases", "{0} compra(s) elegível(eis) (prazo: {1} dias após a compra)" },
            { "SelectPurchaseToReturn", "Selecione uma compra para devolver." },
            { "ErrorReturningPurchase", "Erro ao devolver: {0}" },
            { "RequestBooksTitle", "Requisições / Empréstimos" },
            { "RequestBooks", "Requisitar livros" },
            { "DaysToReturn", "Dias para devolver (0-21):" },
            { "FineWarning", "Multa de 2€ por semana após o prazo. Apenas 1 empréstimo ativo por utilizador." },
            { "LoginToRequest", "Inicie sessão para requisitar livros." },
            { "ActiveLoanWarning", "Já tem um empréstimo ativo. Devolva o livro no histórico de empréstimos antes de requisitar outro." },
            { "ActiveLoan", "Empréstimo ativo" },
            { "ErrorLoadingBooks", "Erro ao carregar livros: {0}" },
            { "BookOutOfStock", "Este livro está esgotado. Use a opção Reservar." },
            { "NoStock", "Sem stock" },
            { "ConfirmRequest", "Confirmar requisição" },
            { "RequestConfirm", "Deseja requisitar \"{0}\"?\n\nPrazo de devolução: {1} dias.\nMulta de 2€ por semana após o prazo." },
            { "RequestSuccess", "Livro requisitado com sucesso!\nDevolução prevista em {0} dias.\n\nConsulte o histórico em \"Histórico de Empréstimos\"." },
            { "BookAvailable", "Este livro está disponível. Use Requisitar em vez de Reservar." },
            { "StockAvailable", "Stock disponível" },
            { "ConfirmReservation", "Confirmar reserva" },
            { "ReserveConfirm", "Deseja reservar \"{0}\"?\n\nSerá notificado quando o livro estiver disponível." },
            { "ReservationSuccess", "Reserva efetuada com sucesso!\nSerá notificado quando o livro estiver em stock." },
            { "ErrorRequesting", "Erro: {0}" },
            { "Stock", "Stock" },
            { "Status", "Estado" },
            { "Loan", "Empréstimo" },
            { "Request", "Requisitar" },
            { "Reservation", "Reserva" },
            { "Reserve", "Reservar" },
            { "RegisterTitle", "Registar Utilizador" },
            { "PasswordMinCharsRegister", "A password deve ter mais de 6 caracteres" },
            { "InvalidEmailRegister", "Email inválido" },
            { "PasswordComplexityRegister", "A password deve conter pelo menos uma letra maiúscula, uma letra minúscula, um número e um caracter especial" },
            { "Phone9Digits", "Número de telefone tem de ter 9 dígitos" },
            { "PhoneExists", "Número de telefone já existe" },
            { "UserRegistered", "Utilizador ({0}) registado com sucesso!" },
            { "EmailExists", "Email já existe" },
            { "FillAllFields", "Preencha todos os campos" },
            { "RecoverPasswordTitle", "Recuperar Password" },
            { "EnterEmail", "Por favor, introduza o seu email." },
            { "NoAccountWithEmail", "Não existe nenhuma conta com este email." },
            { "CodeSent", "Código de confirmação enviado para o seu email!" },
            { "ErrorSendingEmail", "Erro ao enviar email: {0}" },
            { "EnterCode", "Por favor, introduza o código de confirmação." },
            { "CodeValidated", "Código validado com sucesso!" },
            { "IncorrectCode", "Código incorreto. Por favor, tente novamente." },
            { "FillPasswordFields", "Por favor, preencha ambos os campos de password." },
            { "PasswordMin4Chars", "A password deve ter no mínimo 4 caracteres." },
            { "PasswordMax20Chars", "A password deve ter no máximo 20 caracteres." },
            { "PasswordsNotMatch", "As passwords não coincidem." },
            { "PasswordResetSuccess", "Password alterada com sucesso! Pode agora fazer login com a nova password." },
            { "ErrorChangingPassword", "Erro ao alterar password: {0}" },
            { "AdminMenuTitle", "Menu Administrador" },
            { "Statistics", "Estatísticas: {0} ativos, {1} reservas" },
            { "FinancialManagement", "Gestão Financeira: {0:C2} em multas" },
            { "LoginToViewNotifications", "Inicie sessão para ver notificações." },
            { "ErrorOpeningBrowser", "Não foi possível abrir o navegador: {0}" },
            { "LoginToAccessWallet", "Inicie sessão para aceder à Carteira Digital." },
            { "Wallet", "Carteira" }
        };

        private static readonly Dictionary<string, string> En = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "SettingsTitle", "Settings" },
            { "Theme", "Theme:" },
            { "ThemeLight", "Light" },
            { "ThemeDark", "Dark" },
            { "Fullscreen", "Fullscreen reading mode:" },
            { "Font", "Font:" },
            { "FontSize", "Size (pt):" },
            { "AutoLogout", "Disconnect timer:" },
            { "Language", "Language:" },
            { "Save", "Save" },
            { "Cancel", "Cancel" },
            { "Reset", "Restore Defaults" },
            { "RestoreLanguage", "Return to original language" },
            { "Never", "Never" },
            { "Saved", "Settings saved." },
            { "Success", "Success" },
            { "ResetConfirm", "Restore defaults will reset all preferences. Continue?" },
            { "Confirm", "Confirm" },
            { "NoOriginalLanguage", "Original language is not defined." },
            { "Info", "Information" },
            { "LanguageRestored", "Language restored to original." },
            { "Logout", "Logout" },
            { "Books", "Books" },
            { "Profile", "Profile" },
            { "Help", "Help" },
            { "Loans", "Requests/Loans" },
            { "PurchaseHistory", "Purchase History" },
            { "LoanHistory", "Loan History" },
            { "Reservations", "Reservations" },
            { "Assistant", "Assistant" },
            { "AutoLogoutTitle", "Session expired" },
            { "AutoLogoutMessage", "Your session was ended due to inactivity." },
            { "Close", "Close" },
            { "BooksInCart", "Books ({0} in cart)" },
            { "Email", "Email:" },
            { "Password", "Password:" },
            { "Login", "Login" },
            { "Welcome", "Welcome" },
            { "Enter", "Enter" },
            { "Register", "Register" },
            { "ForgotPassword", "Forgot password?" },
            { "NoAccount", "Don't have an account?" },
            { "WalletTitle", "Digital Wallet" },
            { "WalletAccess", "Digital Wallet Access" },
            { "EnterPassword", "Enter your Password:" },
            { "MyWallet", "My Wallet" },
            { "CurrentBalance", "Current Balance: {0:F2}€" },
            { "ChangePaymentMethod", "Change Payment Method" },
            { "ConfigurePayment", "Configure Payment" },
            { "SelectMethod", "Select the desired method:" },
            { "PayPalEmail", "PayPal Email:" },
            { "PhoneNumber", "Phone Number:" },
            { "AccountIBAN", "Account IBAN:" },
            { "AppleID", "Apple ID:" },
            { "SaveChanges", "Save Changes" },
            { "Back", "Back" },
            { "AddFunds", "Add Funds" },
            { "EnterAmount", "Enter the amount to load into wallet (€):" },
            { "CurrentBalanceLabel", "Current balance: {0:F2}€" },
            { "MinValue", "Minimum value: 1.00€ | Maximum value: 1000.00€" },
            { "ConfirmButton", "CONFIRM" },
            { "CancelButton", "CANCEL" },
            { "ConfirmLoading", "Confirm Loading" },
            { "ConfirmLoadingMsg", "Confirm loading of {0:F2}€?\n\nCurrent balance: {1:F2}€\nNew balance: {2:F2}€" },
            { "InvalidValue", "Invalid value" },
            { "EnterValidValue", "Enter a valid value greater than zero." },
            { "MinValueError", "The minimum value is 1.00€." },
            { "MaxValueError", "The maximum value is 1000.00€." },
            { "DefinePassword", "Define Password" },
            { "DefinePasswordMsg", "Define your Digital Wallet access password:" },
            { "PasswordRequirements", "• Minimum 4 characters\n• Maximum 20 characters\n• Can contain letters, numbers and symbols" },
            { "Exit", "EXIT" },
            { "PasswordDefined", "Password defined successfully!" },
            { "ChangePassword", "Change Password" },
            { "CurrentPassword", "Current Password:" },
            { "NewPassword", "New Password:" },
            { "Change", "CHANGE" },
            { "CurrentPasswordIncorrect", "Current password incorrect!" },
            { "PasswordChanged", "Password changed successfully!" },
            { "ConfirmChange", "Confirm Change" },
            { "AreYouSureChangePassword", "Are you sure you want to change your password?" },
            { "PleaseEnterPassword", "Please enter the password." },
            { "PasswordCannotBeEmpty", "Password cannot be empty. Try again." },
            { "PasswordMinChars", "Password must have a minimum of 4 characters." },
            { "PasswordMaxChars", "Password must have a maximum of 20 characters." },
            { "WelcomeToWallet", "Welcome to your Digital Wallet!" },
            { "AuthenticationSuccessful", "Authentication Successful" },
            { "AttemptsExceeded", "Access attempts exceeded!\nThe application will be closed." },
            { "AccessBlocked", "Access Blocked" },
            { "PasswordIncorrect", "Password incorrect!\n\nRemaining attempts: {0}" },
            { "AuthenticationError", "Authentication Error" },
            { "SelectPaymentMethod", "Please select a payment method." },
            { "ValidationWarning", "Validation Warning" },
            { "MethodConfigured", "Method [{0}] configured successfully!\nData saved: {1}" },
            { "FillPaymentField", "Please fill in the payment method data field." },
            { "InsufficientBalance", "Insufficient balance to complete purchase." },
            { "PurchaseSuccessful", "Purchase successful: {0}" },
            { "FundsAdded", "Funds added and saved successfully: +{0:F2}€\n\nCurrent balance: {1:F2}€" },
            { "ValueMustBePositive", "The value to add must be positive." },
            { "CartTitle", "Shopping Cart" },
            { "CartInfo", "The cart is only for purchases. To request or reserve, use Requests." },
            { "ID", "ID" },
            { "Title", "Title" },
            { "Author", "Author" },
            { "Publisher", "Publisher" },
            { "Price", "Price" },
            { "Qty", "Qty" },
            { "Subtotal", "Subtotal" },
            { "Remove", "Remove" },
            { "Total", "Total: {0:C2} ({1} items)" },
            { "RemoveConfirm", "Do you want to remove this book from the cart?" },
            { "Confirmation", "Confirmation" },
            { "QtyGreaterThanZero", "The quantity must be greater than 0." },
            { "InsufficientStock", "Insufficient stock" },
            { "CartEmpty", "The cart is empty!" },
            { "LoginToPurchase", "Please login to complete the purchase." },
            { "InsufficientBalanceCart", "Insufficient balance in wallet. Total: {0:C2}" },
            { "InsufficientBalanceTitle", "Insufficient balance" },
            { "PurchaseCompleted", "Purchase completed successfully!" },
            { "ReceiptError", "Error sending receipt: {0}" },
            { "PurchaseError", "Error completing purchase: {0}" },
            { "Error", "Error" },
            { "ClearCartConfirm", "Do you want to clear the entire cart?" },
            { "Requests", "Requests" },
            { "ProfileTitle", "Profile" },
            { "EditProfile", "Edit" },
            { "SaveProfile", "Save" },
            { "EditPassword", "Edit Password" },
            { "ConfirmIdentity", "You need to confirm your identity to activate edit mode." },
            { "ConfirmationRequired", "Confirmation Required" },
            { "EditModeActivated", "Edit mode activated. You can now change your data and click on the profile photo." },
            { "ClickEditToChangePhoto", "Click 'Edit' to be able to change the profile photo." },
            { "RestrictedAccess", "Restricted Access" },
            { "ViewPasswordFirst", "To view or change the password, first click 'Edit'." },
            { "InvalidPhoneDigits", "Invalid phone number. Only digits are allowed." },
            { "InvalidPhoneLength", "Invalid phone number. Must contain exactly 9 digits." },
            { "NameEmailRequired", "Name and Email fields cannot be empty." },
            { "InvalidEmail", "Invalid email address. Make sure it contains '@' and '.'." },
            { "PasswordMinLength", "The password must contain at least 6 characters." },
            { "PasswordComplexity", "The password must contain at least one uppercase letter, one lowercase letter, one number and one special character" },
            { "PasswordNoSpaces", "The password cannot contain blank spaces" },
            { "DataUpdated", "Data updated successfully!" },
            { "NoChanges", "No changes were detected." },
            { "Information", "Information" },
            { "BookHistory", "Book History" },
            { "PurchaseHistoryTitle", "Purchase History" },
            { "LoginToViewHistory", "Please login to view purchase history." },
            { "NoPurchases", "No purchases recorded" },
            { "PurchasesCount", "{0} purchase(s)" },
            { "ReturnedCount", "{0} returned" },
            { "SortError", "Could not sort: invalid data or column not found." },
            { "LoginToReturn", "Please login to return purchases." },
            { "ReturnPurchase", "Return Purchase" },
            { "LoanHistoryTitle", "Loan History" },
            { "LoginToViewLoans", "Please login to view loan history." },
            { "ReturnBook", "Return book" },
            { "NoActiveLoans", "No active loans" },
            { "ActiveLoans", "{0} active loan(s)" },
            { "ActiveAndOverdue", "{0} active - {1} overdue (fine: 2€/week)" },
            { "SelectLoanToReturn", "Select a loan to return." },
            { "SelectActiveLoan", "Select an active loan to return." },
            { "LoanReturn", "Loan Return" },
            { "ErrorReturning", "Error returning: {0}" },
            { "SelectRejectedLoan", "Select a rejected loan to pay the fine." },
            { "OnlyRejectedHaveFine", "Only rejected loans have a fine for damaged book." },
            { "ConfirmFinePayment", "Confirm Payment" },
            { "PayFineConfirm", "Pay the fine for damaged book \"{0}\"?\n\nAfter payment, the book will be returned." },
            { "FinePaid", "Fine paid successfully! The book has been returned." },
            { "ErrorPayingFine", "Error paying fine: {0}" },
            { "ReturnPurchaseTitle", "Purchase Return" },
            { "NoEligiblePurchases", "No eligible purchases in the first {0} days" },
            { "EligiblePurchases", "{0} eligible purchase(s) (deadline: {1} days after purchase)" },
            { "SelectPurchaseToReturn", "Select a purchase to return." },
            { "ErrorReturningPurchase", "Error returning: {0}" },
            { "RequestBooksTitle", "Requests / Loans" },
            { "RequestBooks", "Request books" },
            { "DaysToReturn", "Days to return (0-21):" },
            { "FineWarning", "Fine of 2€ per week after deadline. Only 1 active loan per user." },
            { "LoginToRequest", "Please login to request books." },
            { "ActiveLoanWarning", "You already have an active loan. Return the book in loan history before requesting another." },
            { "ActiveLoan", "Active Loan" },
            { "ErrorLoadingBooks", "Error loading books: {0}" },
            { "BookOutOfStock", "This book is out of stock. Use the Reserve option." },
            { "NoStock", "No stock" },
            { "ConfirmRequest", "Confirm request" },
            { "RequestConfirm", "Do you want to request \"{0}\"?\n\nReturn deadline: {1} days.\nFine of 2€ per week after deadline." },
            { "RequestSuccess", "Book requested successfully!\nExpected return in {0} days.\n\nCheck history in \"Loan History\"." },
            { "BookAvailable", "This book is available. Use Request instead of Reserve." },
            { "StockAvailable", "Stock available" },
            { "ConfirmReservation", "Confirm reservation" },
            { "ReserveConfirm", "Do you want to reserve \"{0}\"?\n\nYou will be notified when the book is available." },
            { "ReservationSuccess", "Reservation made successfully!\nYou will be notified when the book is in stock." },
            { "ErrorRequesting", "Error: {0}" },
            { "Stock", "Stock" },
            { "Status", "Status" },
            { "Loan", "Loan" },
            { "Request", "Request" },
            { "Reservation", "Reservation" },
            { "Reserve", "Reserve" },
            { "RegisterTitle", "Register User" },
            { "PasswordMinCharsRegister", "The password must have more than 6 characters" },
            { "InvalidEmailRegister", "Invalid email" },
            { "PasswordComplexityRegister", "The password must contain at least one uppercase letter, one lowercase letter, one number and one special character" },
            { "Phone9Digits", "Phone number must have 9 digits" },
            { "PhoneExists", "Phone number already exists" },
            { "UserRegistered", "User ({0}) registered successfully!" },
            { "EmailExists", "Email already exists" },
            { "FillAllFields", "Fill all fields" },
            { "RecoverPasswordTitle", "Recover Password" },
            { "EnterEmail", "Please enter your email." },
            { "NoAccountWithEmail", "No account exists with this email." },
            { "CodeSent", "Confirmation code sent to your email!" },
            { "ErrorSendingEmail", "Error sending email: {0}" },
            { "EnterCode", "Please enter the confirmation code." },
            { "CodeValidated", "Code validated successfully!" },
            { "IncorrectCode", "Incorrect code. Please try again." },
            { "FillPasswordFields", "Please fill both password fields." },
            { "PasswordMin4Chars", "The password must have at least 4 characters." },
            { "PasswordMax20Chars", "The password must have at most 20 characters." },
            { "PasswordsNotMatch", "The passwords do not match." },
            { "PasswordResetSuccess", "Password changed successfully! You can now login with the new password." },
            { "ErrorChangingPassword", "Error changing password: {0}" },
            { "AdminMenuTitle", "Admin Menu" },
            { "Statistics", "Statistics: {0} active, {1} reservations" },
            { "FinancialManagement", "Financial Management: {0:C2} in fines" },
            { "LoginToViewNotifications", "Please login to view notifications." },
            { "ErrorOpeningBrowser", "Could not open browser: {0}" },
            { "LoginToAccessWallet", "Please login to access Digital Wallet." },
            { "Wallet", "Wallet" }
        };

        // NOTE: assume Config and ConfigManager exist elsewhere in the project.
        public static bool IsEnglish(Config cfg)
        {
            return cfg != null && cfg.Language != null
                && cfg.Language.Equals("en", StringComparison.OrdinalIgnoreCase);
        }

        public static string T(string key, Config cfg = null)
        {
            cfg = cfg ?? ConfigManager.Current;
            var dict = IsEnglish(cfg) ? En : Pt;
            string value;
            return dict.TryGetValue(key, out value) ? value : key;
        }

        public static string LogoutOptionLabel(int minutes, Config cfg = null)
        {
            if (minutes <= 0) return T("Never", cfg);
                return string.Format("{0} min", minutes);
        }
    }
}